name: Debugging job
on:
  workflow_dispatch:
  #release:
  #  types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install JDK
      # Configure the maven settings.xml and add a server entry with maven central token username/password and GPG private key
      # The server-username, server-password and gpg-passphrase are declared as env variables.
      - name: Set up Java and settings.xml to access Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Check the gpg key, sign a file
        run: |
          gpg --list-keys
          echo "thisisafiletosign" > thisisafiletosign.txt
          rm thisisafiletosign.txt.asc
          gpg --local-user snowdrop-core@redhat.com --armor --detach-sign --status-fd 1 --batch --no-tty --pinentry-mode error --output thisisafiletosign.txt
          ls -la
          cat thisisafiletosign.txt.asc

      - name: 'Sign the files of the module: narayana-spring-boot-core'
        run: |
         cd narayana-spring-boot-core
         mvn gpg:sign -Prelease
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}